### ISSUE TITLE
LCD I2C interface with Raspberry Pi 3B

### ISSUE THREAD

**Issue by parthkharade** [parthkharade/ECEN-5713-FinalProject#3]
* Use the Linux I2C driver to interface the LCD with the Raspberry Pi 3B
* Blockers  : #1 
* DoD : Can display text on the 20x4 LCD Display.

**Comment by pranjalgupta1901** [comment]
# Work Done
-  Added I2c support in Buildroot image to interface the LCD 20x4
- Wrote LCD Driver and Its Makefile which uses i2c-dev module to communicate with the LCD
- Added Package directory files to fetch the code, make and install it in usr/bin.
- Tested the driver with a test file which also gets installed in the usr/bin.



![Image](https://github.com/parthkharade/ECEN-5713-FinalProject/assets/83120222/a3592506-be03-449d-8739-7391bb1fd79a)



![Image](https://github.com/parthkharade/ECEN-5713-FinalProject/assets/83120222/29481897-c837-4efd-9e65-1fee27ef9df8)




![Image](https://github.com/parthkharade/ECEN-5713-FinalProject/assets/83120222/c62b1630-2e0d-454d-89e0-e53a1240dda3)



# Blockers
- LCD in 8 Bit mode : LCD was not working in 8 bit mode on RPI. I referred LCD datasheet for the init sequence and I wrote the same sequence in Arduino. In Arduino, it was working and therefore I used logic analyzer to detect the issue but was not able to find it. Therefore went to work on 4 bit mode which is working.


![Image](https://github.com/parthkharade/ECEN-5713-FinalProject/assets/83120222/31a6e9a6-f76c-4743-a26b-2f3b01cda32a)
