### ISSUE TITLE
GPIO Button Integration Using Raspberry Pi 3B

### ISSUE THREAD

**Issue by parthkharade** [parthkharade/ECEN-5713-FinalProject#4]
Use the linux GPIO library to interface buttons with the RPi 3B.

* Blockers : #1 .
* DoD : Can read button states.

**Comment by pranjalgupta1901** [comment]
# Work Done
- Wrote GPIO driver which includes function to export, set direction and reads the GPIO value.
- I am able to read the button the status using the library functions which i wrote.
- Installed the gpio library in Rpi using Buildroot image.

https://github.com/pranjalgupta1901/ECEN-5713-Final-Project/tree/ba1fd158298f7a4598ee1a395e2efb659c4b0375
https://github.com/cu-ecen-aeld/final-project-pranjalgupta1901/tree/29e03ef02a6a6401a6fde9a2e7e672385ae23721
