### ISSUE TITLE
Socket Client and Server Development for Raspberry Pi 3B

### ISSUE THREAD

**Issue by parthkharade** [parthkharade/ECEN-5713-FinalProject#7]
* Socket Server : Listens for incoming streaming data.
* Socket Client : Sends GPIO commands to RPi.

* Blockers : #14 
* DoD : Can successfully send data to a test server and can receive data from a test client. Testing can be done by sending and receiving data to and from a local process.

**Comment by pranjalgupta1901** [comment]
- Wrote the client part code during sprint 2 period for getting the Spotify related data.
- Testing to be done once the server side is done.
- Note: Pushing the remaining part which is testing to Sprint 3.

**Comment by pranjalgupta1901** [comment]
# Work Done
- Completed and tested by successfully sending and receiving data between the client and server

https://github.com/pranjalgupta1901/ECEN-5713-Final-Project/tree/ba1fd158298f7a4598ee1a395e2efb659c4b0375
https://github.com/cu-ecen-aeld/final-project-pranjalgupta1901/tree/29e03ef02a6a6401a6fde9a2e7e672385ae23721

![Image](https://github.com/parthkharade/ECEN-5713-FinalProject/assets/83120222/9ce0030c-c70b-486d-a49e-17a536d0c0e3)



![Image](https://github.com/parthkharade/ECEN-5713-FinalProject/assets/83120222/0f10f4ca-7a9b-496e-9560-7aba7c6943d5)
