### ISSUE TITLE
System Integration RPi 1 and RPi 2

### ISSUE THREAD

**Issue by parthkharade** [parthkharade/ECEN-5713-FinalProject#8]
* Integrate the RPi and BB so that they can successfully exchange data.

* Blockers : #6 #7 #4 #3 

* DoD  
  * RPi can successfully receive commands and issues the corresponding playback request to Spotify. 
  * BB can successfully receive and display live streaming data on the 20x4 LCD display.

**Comment by pranjalgupta1901** [comment]
# Work Done
- Completed the integration of code for both Raspberry Pi 1 and Raspberry Pi 2. This includes fetching song data from Spotify and transferring it via a socket to the other Raspberry Pi, which acts as a server. The server Raspberry Pi receives the data and displays it on a 20x4 i2c-based LCD screen. Additionally, it sends back control commands such as play and pause when a GPIO button is pressed.

https://github.com/pranjalgupta1901/ECEN-5713-Final-Project/tree/ba1fd158298f7a4598ee1a395e2efb659c4b0375
https://github.com/cu-ecen-aeld/final-project-pranjalgupta1901/tree/29e03ef02a6a6401a6fde9a2e7e672385ae23721

![Image](https://github.com/parthkharade/ECEN-5713-FinalProject/assets/83120222/41122131-da49-4d35-9e05-48551aa0832f)
